
### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.
spring.jmx:
   enabled: false
   
spring.thymeleaf:
   cache:false

#spring.datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:bootexample;MODE=MySQL;DB_CLOSE_ON_EXIT=TRUE;
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scotch2?createDatabaseIfNotExist=true
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate.ddl-auto:  update

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-Demo
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

---
spring:
  profiles: test

    
 
